/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yiyaowen_javar_c_SyntaxParser */

#ifndef _Included_com_yiyaowen_javar_c_SyntaxParser
#define _Included_com_yiyaowen_javar_c_SyntaxParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yiyaowen_javar_c_SyntaxParser
 * Method:    fillSyntaxParseInfo
 * Signature: (Lcom/yiyaowen/javar/c_SyntaxParseInfo;Ljava/lang/String;[Ljava/lang/String;I[CI)V
 */
JNIEXPORT void JNICALL Java_com_yiyaowen_javar_c_1SyntaxParser_fillSyntaxParseInfo
  (JNIEnv *, jclass, jobject, jstring, jobjectArray, jint, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
